services:
  notepadd:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notepadd-dev
    ports:
      - "3002:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - /run/media/arch_btw/USB28/notepadd-repo:/app/.notepadd-repo
      - /run/media/arch_btw/USB28/notepadd-volume:/app/.notepadd-volume
