services:
  notepadd:
    image: docker.io/nullruntimedev/noteadd:1.0.1
    container_name: notepadd
    ports:
      - "3002:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - notepadd-repo:/app/.notepadd-repo
      - ./.env:/app/.env

volumes:
  notepadd-repo: